---
- hosts: servers
  become: true

  pre_tasks:
    - include_tasks: "set-up-ca-cert.yaml"

  roles:
    - prometheus.prometheus.prometheus
    
  vars:
    # prep
    _targets: "{{ groups['all'] | product([':9100']) | map('join') | list }}"

    # prometheus.prometheus.prometheus
    prometheus_targets:
      node:
        - targets: _targets
          labels:               
            env: lab            
    prometheus_scrape_configs:
      - job_name: "prometheus"    
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"
              
      - job_name: "node-file-servicediscovery"
        scheme: https
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from prometheus_targets

- hosts: all
  become: true
  
  pre_tasks:
    - set_fact:
        server_name: "{{ groups['servers'][0] }}"
          
    - include_tasks: "set-up-agent-cert.yaml"

  roles:
    - prometheus.prometheus.node_exporter
    
  vars:
    node_exporter_web_listen_address: "{{ inventory_hostname }}:9100"
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.pem
      key_file: /etc/node_exporter/tls.key

      