---
- hosts: servers
  become: true
  roles:
    - grafana.grafana.grafana

  vars:
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ inventory_hostname }}:9090'
        basicAuth: false  
