---
- hosts: all
  become: true
  roles:
    - grafana

  vars:
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ prometheus_web_listen_address }}'
        basicAuth: false  
