---
- hosts: all
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:  # This is a base file name. File is located in "{{ prometheus_config_dir }}/file_sd/<<BASENAME>>.yml"
        - targets:              #
            - localhost:9100    # All this is a targets section in file_sd format
          labels:               #
            env: lab            #
    prometheus_scrape_configs:
      - job_name: "prometheus"    
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"
      - job_name: "example-node-file-servicediscovery"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from prometheus_targets        